### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by terabyte25**
c0da makes it canon

### CODE REVIEW

**Comment by terabyte25** [comment]
haha xdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd this adds support for fallout 76 guise

**Comment by terabyte25** [comment]
hey guise look at DIS meme :DDDDDDDDD ### WHERES YOUR UNIFORM

**Comment by terabyte25** [comment]
why did it bail :DDDDDDDDDddDD

**Comment by testman42** [comment]
top meem my dude :rofl:

**Comment by terabyte25** [comment]
does I have to change build directory from openscenegraph to osg :DDDD

**Pull request closed without merging**
